CREATE OR REPLACE VIEW vw_menu_raiz AS
SELECT m.ID_MENU AS ID_MENU,
       m.NOM_MENU AS NOM_MENU,
       m.DSC_MENU AS DSC_MENU,
       m.DSC_URL AS DSC_URL,
       m.FLG_ATIVO AS FLG_ATIVO,
       m.ID_PAGINA AS ID_PAGINA,
       m.ID_MENU_PAI AS ID_MENU_PAI,
       m.NUM_INDEX AS NUM_INDEX
  FROM tb_menu AS m
 WHERE m.ID_MENU_PAI IS NULL
 ORDER BY m.NUM_INDEX,
          m.NOM_MENU